spring.application.name=falae.dev-api

#server.address=0.0.0.0
#server.port=8081

#Datasource
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:falae_db_v2}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:senha123}

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

#JWT
jwt.secret=${TOKEN_SECRET_KEY:zT#xVnu_-EL5E188~'FPv,BNNxMMr!ii#8fN#@%$kZQANBD.fuR6@cNQwZe-VXUe;mT}o2g$y;-FBcB~s<.*m,$/}
jwt.expiration=86400000
jwt.email-verification-expiration=86400000

#Logging
logging.level.com.example=WARN

#flyway
spring.flyway.locations=classpath:db/migration/postgres
spring.flyway.enabled=true
spring.flyway.default-schema=public
spring.flyway.schemas=public

app.frontend-url=https://falae.dev

#cloudflare r2
r2.endpoint=${R2_ENDPOINT:https://123456789.r2.cloudflarestorage.com}
r2.access-key=${R2_ACCESS_KEY:123123123123}
r2.secret-key=${R2_SECRET_KEY:123123123123}
r2.region=auto
r2.bucket=${R2_BUCKET:r2}
r2.public-url=${R2_PUBLIC_URL:https://r2.falae.dev}


cookie.setSecure=${COOKIE_SET_SECURE:false}
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173,http://192.168.1.75:5173}

#Google OAuth
google.client-id=${GOOGLE_CLIENT_ID:123456789.apps.googleusercontent.com}

#Upload
upload.image.max-size-kb=${UPLOAD_IMAGE_MAX_SIZE_KB:600}

#ZeptoMail
zeptomail.api-url=${ZEPTOMAIL_API_URL:https://api.zeptomail.com/v1.1/email}
zeptomail.api-key=${ZEPTOMAIL_API_KEY:xxxxxxxxxxxxxxxxxxxxx}
zeptomail.from-address=${ZEPTOMAIL_FROM_ADDRESS:noreply@falae.dev}
zeptomail.from-name=${ZEPTOMAIL_FROM_NAME:Falae.dev}